# DO NOT MODIFY THIS FILE!
# THIS FILE WAS AUTOGENERATED BY ISESTEROIDS AND WILL BE OVERWRITTEN WHEN YOU EXPORT FUNCTIONS TO THIS MODULE.
. $PSScriptRoot\Connect-Email.ps1
. $PSScriptRoot\Connect-Exch.ps1
. $PSScriptRoot\Connect-O365.ps1
. $PSScriptRoot\Disable-OnPremMailUser.ps1
. $PSScriptRoot\Disconnect-Email.ps1
. $PSScriptRoot\Disconnect-Exch.ps1
. $PSScriptRoot\Disconnect-O365.ps1
. $PSScriptRoot\Enable-OnPremMailbox.ps1
. $PSScriptRoot\Get-MailboxStatus.ps1
. $PSScriptRoot\Invoke-CloudToExch.ps1
. $PSScriptRoot\Invoke-ExchToCloud.ps1
. $PSScriptRoot\Start-Dirsync.ps1
